data = ["1	$National Bureau of Economic Research (NBER) $Cambridge, Massachusetts (USA)",
"2	$Department of Economics, Harvard University $Cambridge, Massachusetts (USA)",
"3	$London School of Economics (LSE) $London, United Kingdom",
"4	$Economics Department, Massachusetts Institute of Technology (MIT) $Cambridge, Massachusetts (USA)",
"5	$World Bank Group $Washington, District of Columbia (USA)",
"6	$Booth School of Business, University of Chicago $Chicago, Illinois (USA)",
"7	$International Monetary Fund (IMF) $Washington, District of Columbia (USA)",
"8	$Department of Economics, University of California-Berkeley $Berkeley, California (USA)",
"9	$Department of Economics, University of Chicago $Chicago, Illinois (USA)",
"10	$Department of Economics, Princeton University $Princeton, New Jersey (USA)",
"11	$Paris School of Economics $Paris, France",
"12	$Department of Economics, Stanford University $Stanford, California (USA)",
"13	$Graduate School of Business, Stanford University $Stanford, California (USA)",
"14	$European Central Bank $Frankfurt am Main, Germany",
"15	$Federal Reserve Board (Board of Governors of the Federal Reserve System) $Washington, District of Columbia (USA)",
"16	$Toulouse School of Economics (TSE) $Toulouse, France",
"17	$Harvard Kennedy School, Harvard University $Cambridge, Massachusetts (USA)",
"18	$Department of Economics, New York University (NYU) $New York City, New York (USA)",
"19	$Department of Economics, School of Arts and Sciences, Columbia University $New York City, New York (USA)",
"20	$Institute of Labor Economics (IZA) $Bonn, Germany",
"21	$Università Commerciale Luigi Bocconi $Milano, Italy",
"22	$Department of Economics, Oxford University $Oxford, United Kingdom",
"23	$Economics Department, Yale University $New Haven, Connecticut (USA)",
"---	$Economics Research, World Bank Group $Washington, District of Columbia (USA)",
"24	$Barcelona School of Economics (BSE) $Barcelona, Spain",
"25	$Department of Economics, University of Pennsylvania $Philadelphia, Pennsylvania (USA)",
"26	$Monash Business School, Monash University $Melbourne, Australia",
"27	$Economics Department, Brown University $Providence, Rhode Island (USA)",
"28	$Department of Economics, Boston University $Boston, Massachusetts (USA)",
"29	$Stern School of Business, New York University (NYU) $New York City, New York (USA)",
"30	$Graduate School of Business, Columbia University $New York City, New York (USA)",
"31	$Bank for International Settlements (BIS) $Basel, Switzerland",
"32	$Banco de la Republica de Colombia $Bogotá, Colombia",
"33	$Federal Reserve Bank of New York $New York City, New York (USA)",
"34	$Department of Economics, University College London (UCL) $London, United Kingdom",
"35	$Sloan School of Management, Massachusetts Institute of Technology (MIT) $Cambridge, Massachusetts (USA)",
"---	$Economics Department, London School of Economics (LSE) $London, United Kingdom",
"36	$Wharton School of Business, University of Pennsylvania $Philadelphia, Pennsylvania (USA)",
"37	$Department of Economics, University of California-San Diego (UCSD) $La Jolla, California (USA)",
"38	$Banca d'Italia $Roma, Italy",
"39	$Department of Economics, Northwestern University $Evanston, Illinois (USA)",
"40	$Department of Economics, University of Southern California $Los Angeles, California (USA)",
"41	$Economics Department, University of Michigan $Ann Arbor, Michigan (USA)",
"42	$Economics Department, Dartmouth College $Hanover, New Hampshire (USA)",
"43	$Sciences économiques, Sciences Po $Paris, France",
"44	$Walter A. Haas School of Business, University of California-Berkeley $Berkeley, California (USA)",
"45	$Centre for Economic Policy Research (CEPR) $London, United Kingdom",
"46	$Wirtschaftswissenschaftliche Fakutält, Universität Zürich $Zürich, Switzerland",
"47	$Department of Economics, University of California-Los Angeles (UCLA) $Los Angeles, California (USA)",
"---	$Finance and Economics Department, Graduate School of Business, Columbia University $New York City, New York (USA)",
"48	$International Food Policy Research Institute (IFPRI) $Washington, District of Columbia (USA)",
"---	$Research and Statistics Group, Federal Reserve Bank of New York $New York City, New York (USA)",
"49	$Vancouver School of Economics, University of British Columbia $Vancouver, Canada",
"50	$Kellogg Graduate School of Management, Northwestern University $Evanston, Illinois (USA)",
"51	$ifo Institut - Leibniz-Institut für Wirtschaftsforschung an der Universität München e.V.  $München, Germany",
"52	$Economics Department, University of Wisconsin-Madison $Madison, Wisconsin (USA)",
"53	$School of Economics and Management, Universiteit van Tilburg $Tilburg, Netherlands",
"54	$Department of Economics, Duke University $Durham, North Carolina (USA)",
"55	$Organisation de Coopération et de Développement Économiques (OCDE) $Paris, France",
"---	$Centre for Economic Performance (CEP), London School of Economics (LSE) $London, United Kingdom",
"56	$Department of Economics, Cornell University $Ithaca, New York (USA)",
"57	$Brookings Institution $Washington, District of Columbia (USA)",
"58	$Department of Economics, University of Toronto $Toronto, Canada",
"59	$Economics Department, Michigan State University $East Lansing, Michigan (USA)",
"---	$Institut für Volkswirtschaftslehre, Wirtschaftswissenschaftliche Fakutält, Universität Zürich $Zürich, Switzerland",
"60	$Department of Economics, Boston College $Chestnut Hill, Massachusetts (USA)",
"61	$Department of Economics, University of Warwick $Coventry, United Kingdom",
"62	$Economics Department, University of California-Davis $Davis, California (USA)",
"63	$Harvard Business School, Harvard University $Cambridge, Massachusetts (USA)",
"64	$Federal Reserve Bank of St. Louis $St. Louis, Missouri (USA)",
"65	$Solvay Brussels School of Economics and Management, Université Libre de Bruxelles $Bruxelles, Belgium",
"66	$Anderson Graduate School of Management, University of California-Los Angeles (UCLA) $Los Angeles, California (USA)",
"67	$Faculteit Economie en Bedrijfskunde, Rijksuniversiteit Groningen $Groningen, Netherlands",
"68	$Louvain Institute of Data Analysis and Modelling in Economics and Statistics (LIDAM), Université Catholique de Louvain $Louvain-la-Neuve, Belgium",
"---	$Research Division, Federal Reserve Bank of St. Louis $St. Louis, Missouri (USA)",
"69	$Hoover Institution on War Revolution & Peace, Stanford University $Stanford, California (USA)",
"---	$Department of Economics, Monash Business School, Monash University $Melbourne, Australia",
"70	$DIW Berlin (Deutsches Institut für Wirtschaftsforschung) $Berlin, Germany",
"71	$School of Economics, University of Nottingham $Nottingham, United Kingdom",
"72	$Department of Economics, University of Maryland $College Park, Maryland (USA)",
"73	$Federal Reserve Bank of Chicago $Chicago, Illinois (USA)",
"74	$School of International and Public Affairs (SIPA), Columbia University $New York City, New York (USA)",
"75	$Stockholm School of Economics $Stockholm, Sweden",
"76	$Department of Economics, University of California-Irvine $Irvine, California (USA)",
"---	$Department of Economics, Sciences économiques, Sciences Po $Paris, France",
"77	$Banco de España $Madrid, Spain",
"---	$CentER Graduate School for Economics and Business, School of Economics and Management, Universiteit van Tilburg $Tilburg, Netherlands",
"---	$Departament d'Economia i Empresa, Universitat Pompeu Fabra, Barcelona School of Economics (BSE) $Barcelona, Spain",
"78	$Department of Economics, University of Texas-Austin $Austin, Texas (USA)",
"79	$Dipartimento di Scienze Economiche, Alma Mater Studiorum - Università di Bologna $Bologna, Italy",
"80	$Department of Economics, Vanderbilt University $Nashville, Tennessee (USA)",
"81	$Faculty of Economics, University of Cambridge $Cambridge, United Kingdom",
"82	$Federal Reserve Bank of Minneapolis $Minneapolis, Minnesota (USA)",
"83	$Harris School of Public Policy, University of Chicago $Chicago, Illinois (USA)",
"84	$Department of Economics, Johns Hopkins University $Baltimore, Maryland (USA)",
"85	$School of Business and Economics, Vrije Universiteit Amsterdam $Amsterdam, Netherlands",
"86	$Banque de France $Paris, France",
"87	$School of Management, Yale University $New Haven, Connecticut (USA)",
"88	$Federal Reserve Bank of San Francisco $San Francisco, California (USA)",
"89	$Institut for Økonomi, Aarhus Universitet $Aarhus, Denmark",
"90	$Faculteit Economie en Bedrijfswetenschappen, KU Leuven $Leuven, Belgium",
"91	$Department of Economics, University of Notre Dame $South Bend, Indiana (USA)",
"---	$Economic Studies, Brookings Institution $Washington, District of Columbia (USA)",
"92	$Bank of England $London, United Kingdom",
"93	$Centro de Estudios Monetarios y Financieros (CEMFI) $Madrid, Spain",
"---	$Innocenzo Gasparini Institute for Economic Research (IGIER), Università Commerciale Luigi Bocconi $Milano, Italy",
"94	$Centre de Recherche en Économie et Statistique (CREST) $Palaiseau, France",
"95	$Joint Research Centre, European Commission $Sevilla, Spain",
"96	$Faculteit der Economische Wetenschappen, Erasmus Universiteit Rotterdam $Rotterdam, Netherlands",
"97	$Crawford School of Public Policy, Australian National University $Canberra, Australia",
"---	$Institut d'Économie Industrielle (IDEI), Toulouse School of Economics (TSE) $Toulouse, France",
"98	$Economics Department, Queen's University $Kingston, Canada",
"99	$Department of Economics, University of Western Ontario $London, Canada",
"100	$UNSW Business School, UNSW Sydney $Sydney, Australia",
"101	$Økonomisk Institut, Københavns Universitet $København, Denmark",
"102	$Peter G. Peterson Institute for International Economics (IIE) $Washington, District of Columbia (USA)",
"103	$Department of Economics, University of Virginia $Charlottesville, Virginia (USA)",
"104	$Department of Economics and Related Studies, University of York $York, United Kingdom",
"105	$Economics Department, Georgetown University $Washington, District of Columbia (USA)",
"106	$Faculteit Economie en Bedrijfskunde, Universiteit van Amsterdam $Amsterdam, Netherlands",
"107	$Department of Economics, University of Minnesota $Minneapolis, Minnesota (USA)",
"108	$School of Economics, University of Queensland $Brisbane, Australia",
"109	$Business School, Imperial College $London, United Kingdom",
"110	$École d'Économie d'Aix-Marseille, Aix-Marseille Université $Aix-en-Provence/Marseille, France",
"111	$Department of Economics, University of California-Santa Barbara (UCSB) $Santa Barbara, California (USA)",
"---	$Finance Department, Stern School of Business, New York University (NYU) $New York City, New York (USA)",
"112	$Department of Economics, Pennsylvania State University $State College, Pennsylvania (USA)",
"113	$Federal Reserve Bank of Dallas $Dallas, Texas (USA)",
"114	$Cowles Foundation for Research in Economics, Yale University $New Haven, Connecticut (USA)",
"115	$W.P. Carey School of Business, Arizona State University $Tempe, Arizona (USA)",
"116	$Bank of Canada $Ottawa, Canada",
"117	$London Business School (LBS) $London, United Kingdom",
"118	$Österreichisches Institut für Wirtschaftsforschung (WIFO) $Wien, Austria",
"119	$Tuck School of Business, Dartmouth College $Hanover, New Hampshire (USA)",
"---	$Finance Department, Wharton School of Business, University of Pennsylvania $Philadelphia, Pennsylvania (USA)",
"120	$Deutsche Bundesbank $Frankfurt, Germany",
"121	$Faculty of Business and Economics, University of Melbourne $Melbourne, Australia",
"---	$Economic Research, Federal Reserve Bank of San Francisco $San Francisco, California (USA)",
"122	$Department of Economics, Washington University in St. Louis $St. Louis, Missouri (USA)",
"123	$Norges Handelshøyskole (NHH) $Bergen, Norway",
"124	$Rotman School of Management, University of Toronto $Toronto, Canada",
"125	$Department of Economics, Rutgers University-New Brunswick $New Brunswick, New Jersey (USA)",
"---	$Economics Department, Stern School of Business, New York University (NYU) $New York City, New York (USA)",
"126	$Department of Economics, Ohio State University $Columbus, Ohio (USA)",
"127	$CESifo $München, Germany",
"128	$Olin School of Business, Washington University in St. Louis $St. Louis, Missouri (USA)",
"129	$Inter-American Development Bank $Washington, District of Columbia (USA)",
"---	$Research Department, International Monetary Fund (IMF) $Washington, District of Columbia (USA)",
"130	$Volkswirtschaftliche Fakultät, Ludwig-Maximilians-Universität München $München, Germany",
"131	$Eitan Berglas School of Economics, Tel Aviv University $Tel Aviv, Israel",
"132	$Department of Economics, University of Colorado $Boulder, Colorado (USA)",
"133	$College of Business and Economics, Australian National University $Canberra, Australia",
"---	$European Centre for Advanced Research in Economics and Statistics (ECARES), Solvay Brussels School of Economics and Management, Université Libre de Bruxelles $Bruxelles, Belgium",
"---	$Department of Finance, Kellogg Graduate School of Management, Northwestern University $Evanston, Illinois (USA)",
"134	$Fachbereich Wirtschaftswissenschaft, Goethe Universität Frankfurt am Main $Frankfurt am Main, Germany",
"135	$Economics Department, University of California-Santa Cruz (UCSC) $Santa Cruz, California (USA)",
"136	$Økonomisk institutt, Universitetet i Oslo $Oslo, Norway",
"---	$Center for Operations Research and Econometrics (CORE), Louvain Institute of Data Analysis and Modelling in Economics and Statistics (LIDAM), Université Catholique de Louvain $Louvain-la-Neuve, Belgium",
"137	$Charles H. Dyson School of Applied Economics and Management, College of Agriculture and Life Sciences, Cornell University $Ithaca, New York (USA)",
"138	$Department of Agricultural and Resource Economics, University of California-Berkeley $Berkeley, California (USA)",
"139	$Departamento de Economía, Universidad Carlos III de Madrid $Madrid, Spain",
"---	$Research School of Economics, College of Business and Economics, Australian National University $Canberra, Australia",
"140	$Copenhagen Business School $København, Denmark",
"141	$Department of Commerce, Government of the United States $Washington, District of Columbia (USA)",
"142	$Department of Economics, Hebrew University of Jerusalem $Jerusalem, Israel",
"143	$Fisher College of Business, Ohio State University $Columbus, Ohio (USA)",
"144	$Federal Reserve Bank of Philadelphia $Philadelphia, Pennsylvania (USA)",
"145	$Federal Reserve Bank of Cleveland $Cleveland, Ohio (USA)",
"---	$Research Department, Federal Reserve Bank of Minneapolis $Minneapolis, Minnesota (USA)",
"146	$School of Business and Economics, Maastricht University $Maastricht, Netherlands",
"147	$Tinbergen Instituut $Amsterdam, Netherlands",
"148	$Andrew Young School of Policy Studies, Georgia State University $Atlanta, Georgia (USA)",
"149	$WU Wirtschaftsuniversität Wien $Wien, Austria",
"150	$HEC Paris (École des Hautes Études Commerciales) $Jouy-en-Josas, France",
"---	$Department of Economics, W.P. Carey School of Business, Arizona State University $Tempe, Arizona (USA)",
"151	$Dipartimenti e Istituti di Scienze Economiche, Università Cattolica del Sacro Cuore $Milano/Piacenza, Italy",
"152	$Sussex Business School, University of Sussex $Brighton, United Kingdom",
"153	$Marshall School of Business, University of Southern California $Los Angeles, California (USA)",
"---	$School of Economics, UNSW Business School, UNSW Sydney $Sydney, Australia",
"154	$Mitchell E. Daniels, Jr. School of Business, Purdue University $West Lafayette, Indiana (USA)",
"155	$Wirtschaftswissenschaftlicher Fachbereich, Rheinische Friedrich-Wilhelms-Universität Bonn $Bonn, Germany",
"156	$Department of Economics, George Washington University $Washington, District of Columbia (USA)",
"157	$Department of Economics, University of Washington $Seattle, Washington (USA)",
"158	$Eller College of Management, University of Arizona $Tucson, Arizona (USA)",
"---	$Census Bureau, Department of Commerce, Government of the United States $Washington, District of Columbia (USA)",
"159	$Abteilung für Volkswirtschaftslehre, Universität Mannheim $Mannheim, Germany",
"160	$Department of Economics, McGill University $Montréal, Canada",
"---	$Department of Geography and Environment, London School of Economics (LSE) $London, United Kingdom",
"161	$Faculté des Hautes Études Commerciales (HEC), Université de Lausanne $Lausanne, Switzerland",
"---	$Economics Department, Eller College of Management, University of Arizona $Tucson, Arizona (USA)",
"162	$Adam Smith Business School, University of Glasgow $Glasgow, United Kingdom",
"163	$School of Economics, Faculty of Arts and Social Sciences, University of Sydney $Sydney, Australia",
"---	$Department of Economics, Andrew Young School of Policy Studies, Georgia State University $Atlanta, Georgia (USA)",
"164	$School of Public and International Affairs, Princeton University $Princeton, New Jersey (USA)",
"165	$Université Paris-Dauphine (Paris IX) $Paris, France",
"166	$Department of Economics, University of Pittsburgh $Pittsburgh, Pennsylvania (USA)",
"167	$Facoltà di Economia, Università degli Studi di Roma Tor Vergata $Roma, Italy",
"168	$Istituto Einaudi per l'Economia e la Finanza (EIEF) $Roma, Italy",
"169	$Fakultät für Wirtschaftswissenschaften, Universität Wien $Wien, Austria",
"170	$Sauder School of Business, University of British Columbia $Vancouver, Canada",
"171	$Department of Economics, Tufts University $Medford, Massachusetts (USA)",
"172	$Economics Department, Williams College $Williamstown, Massachusetts (USA)",
"---	$Department of Finance and Business Economics, Marshall School of Business, University of Southern California $Los Angeles, California (USA)",
"173	$Economic Research Service, Department of Agriculture, Government of the United States $Washington, District of Columbia (USA)",
"---	$Economics Department, Organisation de Coopération et de Développement Économiques (OCDE) $Paris, France",
"174	$Federal Reserve Bank of Boston $Boston, Massachusetts (USA)",
"175	$Fuqua School of Business, Duke University $Durham, North Carolina (USA)",
"176	$Resources for the Future (RFF) $Washington, District of Columbia (USA)",
"177	$Ekonomihögskolan, Lunds Universitet $Lund, Sweden",
"178	$Institutet för Näringslivsforskning (IFN) $Stockholm, Sweden",
"179	$Institute for International Economic Studies (IIES), Stockholms Universitet $Stockholm, Sweden",
"180	$Centro Studi di Economia e Finanza (CSEF) $Napoli, Italy",
"181	$Leibniz-Zentrum für Europäische Wirtschaftsforschung (ZEW) $Mannheim, Germany",
"182	$Academia de Studii Economice din Bucureşti $Bucureşti, Romania",
"---	$Dipartimento di Economia Ettore Bocconi, Università Commerciale Luigi Bocconi $Milano, Italy",
"183	$Federal Reserve Bank of Atlanta $Atlanta, Georgia (USA)",
"184	$Department of Economics, University of Illinois at Urbana-Champaign $Urbana-Champaign, Illinois (USA)",
"185	$School of Economics and Finance, Queen Mary University of London $London, United Kingdom",
"186	$Faculty of Economics, University of Tokyo $Tokyo, Japan",
"187	$Department of Economics, Iowa State University $Ames, Iowa (USA)",
"188	$Department of Management, Technology and Economics (D-MTEC), Eidgenössische Technische Hochschule Zürich (ETHZ) $Zürich, Switzerland",
"---	$Centre de Recerca en Economia Internacional (CREI), Barcelona School of Economics (BSE) $Barcelona, Spain",
"189	$Wirtschafts- und Sozialwissenschaftliche Fakultät, Universität zu Köln $Köln, Germany",
"190	$Business School, University of Technology Sydney $Sydney, Australia",
"191	$Department of Economics, Texas A&M University $College Station, Texas (USA)",
"192	$Economics, New York University Abu Dhabi $Abu Dhabi, United Arab Emirates",
"193	$Facultad de Economía y Negocios, Universidad de Chile $Santiago, Chile",
"194	$Ross School of Business, University of Michigan $Ann Arbor, Michigan (USA)",
"195	$Kiel Institut für Weltwirtschaft - Leibniz Zentrum zur Erforschung globaler ökonomischer Herausforderungen (IfW) $Kiel, Germany",
"---	$Department of Economics, Adam Smith Business School, University of Glasgow $Glasgow, United Kingdom",
"196	$Leonard D. Schaeffer Center for Health Policy and Economics, University of Southern California $Los Angeles, California (USA)",
"197	$Handelshögskolan, Göteborgs Universitet $Göteborg, Sweden",
"198	$Athens University of Economics and Business (AUEB) $Athens, Greece",
"199	$Department of Economics, School of Social Sciences, University of Manchester $Manchester, United Kingdom",
"200	$Faculteit Economie en Bedrijfskunde, Universiteit Gent $Gent, Belgium",
"201	$School of Economics, Universitat de Barcelona $Barcelona, Spain",
"202	$Centre d'Économie de la Sorbonne, Université Paris 1 (Panthéon-Sorbonne) $Paris, France",
"203	$Judge Business School, University of Cambridge $Cambridge, United Kingdom",
"---	$Dipartimento di Economia e Finanza, Facoltà di Economia, Università degli Studi di Roma Tor Vergata $Roma, Italy",
"204	$Business School, Deakin University $Melbourne, Australia",
"205	$Economics Department, George Mason University $Fairfax, Virginia (USA)",
"206	$Department of Economics, Simon Fraser University $Burnaby, Canada",
"207	$SKEMA Business School $Lille, France",
"208	$Economics Department, University of Essex $Colchester, United Kingdom",
"209	$Institutul National de Cercetari Economice (INCE), Academia Romana $Bucureşti, Romania",
"210	$Department of Agricultural, Food and Resource Economics, College of Agriculture and Natural Resources, Michigan State University $East Lansing, Michigan (USA)",
"---	$Department of Economics, Mitchell E. Daniels, Jr. School of Business, Purdue University $West Lafayette, Indiana (USA)",
"211	$Federal Reserve Bank of Richmond $Richmond, Virginia (USA)",
"212	$Faculty of Business and Economics, University of Hong Kong $Pokfulam, Hong Kong",
"213	$Nationalekonomiska Institutionen, Uppsala Universitet $Uppsala, Sweden",
"214	$Facoltà di Economia, Sapienza Università di Roma $Roma, Italy",
"215	$Department of Economics, Emory University $Atlanta, Georgia (USA)",
"216	$BI Handelshøyskolen $Oslo, Norway",
"---	$Institutt for samfunnsøkonomi, Norges Handelshøyskole (NHH) $Bergen, Norway",
"217	$School of Economics, University of Edinburgh $Edinburgh, United Kingdom",
"---	$Department of Finance, Fisher College of Business, Ohio State University $Columbus, Ohio (USA)",
"---	$Economic Research, Federal Reserve Bank of Cleveland $Cleveland, Ohio (USA)",
"218	$Division of Social Sciences, California Institute of Technology $Pasadena, California (USA)",
"---	$Research Department, Federal Reserve Bank of Philadelphia $Philadelphia, Pennsylvania (USA)",
"219	$Saïd Business School, Oxford University $Oxford, United Kingdom",
"---	$Finance Unit, Harvard Business School, Harvard University $Cambridge, Massachusetts (USA)",
"220	$Department Volkswirtschaftlehre, Universität Bern $Bern, Switzerland",
"221	$Department of Economics, University of Oregon $Eugene, Oregon (USA)",
"222	$Department of Economics, Indiana University $Bloomington, Indiana (USA)",
"---	$Center for Economic Studies, Census Bureau, Department of Commerce, Government of the United States $Washington, District of Columbia (USA)",
"223	$School of Economics, University College Dublin $Dublin, Ireland",
"---	$Department of Economics, Stockholm School of Economics $Stockholm, Sweden",
"---	$Nationalekonomiska Institutionen, Ekonomihögskolan, Lunds Universitet $Lund, Sweden",
"224	$Department of Economics, University of Birmingham $Birmingham, United Kingdom",
"225	$Department of Economics, National University of Singapore (NUS) $Singapore, Singapore",
"226	$Shanghai Advanced Institute of Finance (SAIF), Shanghai Jiao Tong University $Shanghai, China",
"227	$School of Economics and Political Science, Universität St. Gallen $Sankt Gallen, Switzerland",
"228	$Institut ekonomických studií, Univerzita Karlova v Praze $Praha, Czech Republic",
"---	$Real Estate Department, Wharton School of Business, University of Pennsylvania $Philadelphia, Pennsylvania (USA)",
"---	$Economic Research Department, Federal Reserve Bank of Dallas $Dallas, Texas (USA)",
"229	$Argyros School of Business and Economics, Chapman University $Orange, California (USA)",
"230	$School of Business and Economics, Universidade Nova de Lisboa $Lisboa, Portugal",
"231	$Department of Economics, McMaster University $Hamilton, Canada",
"---	$Economic Research Department, Federal Reserve Bank of Chicago $Chicago, Illinois (USA)",
"---	$Department of Economics, London Business School (LBS) $London, United Kingdom",
"232	$Carol Martin Gatton College of Business and Economics, University of Kentucky $Lexington, Kentucky (USA)",
"233	$Wydział Nauk Ekonomicznych, Uniwersytet Warszawski $Warszawa, Poland",
"234	$College of Business and Behavioral Science, Clemson University $Clemson, South Carolina (USA)",
"235	$Department of Agricultural and Resource Economics, University of Maryland $College Park, Maryland (USA)",
"236	$Department of Economics, International Business School, Brandeis University $Waltham, Massachusetts (USA)",
"237	$Department of Economics, University of Connecticut $Storrs, Connecticut (USA)",
"238	$United Nations University-Maastricht Economic Research Institute of Innovation and Technology (UNU-MERIT) $Maastricht, Netherlands",
"239	$Dipartimento di Economia, Universita Ca Foscari Venezia $Venezia, Italy",
"240	$Cheung Kong Graduate School of Business $Beijing, China",
"---	$John E. Walker Department of Economics, College of Business and Behavioral Science, Clemson University $Clemson, South Carolina (USA)",
"241	$Instituto Superior de Economia e Gestão (ISEG), Universidade de Lisboa $Lisboa, Portugal",
"242	$Robert Schuman Centre for Advanced Studies (RSCAS), European University Institute $Firenze, Italy",
"243	$School of Economics, University of Bristol $Bristol, United Kingdom",
"244	$School of Economics, University of Surrey $Guildford, United Kingdom",
"---	$Finance Area, Fuqua School of Business, Duke University $Durham, North Carolina (USA)",
"244	$Motu: Economic & Public Policy Research $Wellington, New Zealand",
"246	$Department of Economics, University of Calgary $Calgary, Canada",
"247	$International Economics Section, The Graduate Institute of International and Development Studies $Genève, Switzerland",
"248	$Economics Department, University of Rochester $Rochester, New York (USA)",
"249	$Graduate School of Economics and Management, Université Paris-Saclay $Saint-Aubin, France",
"249	$Stanford Institute for Economic Policy Research (SIEPR), Stanford University $Stanford, California (USA)",
"251	$Miami Herbert Business School, University of Miami $Coral Gables, Florida (USA)",
"---	$Economic Research Department, Federal Reserve Bank of Atlanta $Atlanta, Georgia (USA)",
"---	$Departamento de Economía, Facultad de Economía y Negocios, Universidad de Chile $Santiago, Chile",
"252	$Dipartimento di Scienze Economiche e Aziendali Marco Fanno, Università degli Studi di Padova $Padova, Italy",
"253	$Dipartimento di Economia, Management e Metodi Quantitativi (DEMM), Università degli Studi di Milano $Milano, Italy",
"---	$Strategy and Business Economics Division, Sauder School of Business, University of British Columbia $Vancouver, Canada",
"---	$Department of Economics, Sussex Business School, University of Sussex $Brighton, United Kingdom",
"254	$Nationalekonomiska institutionen, Stockholms Universitet $Stockholm, Sweden",
"255	$Department of Economics, Maxwell School, Syracuse University $Syracuse, New York (USA)",
"256	$HEC Montréal (École des Hautes Études Commerciales) $Montréal, Canada",
"257	$Dipartimento di Economia e Statistica Cognetti de Martiis, Università degli Studi di Torino $Torino, Italy",
"258	$Institute for Fiscal Studies (IFS) $London, United Kingdom",
"259	$Division of Economics, Seoul National University $Seoul, South Korea",
"260	$Terry College of Business, University of Georgia $Athens, Georgia (USA)",
"261	$Bordeaux Sciences Économiques (BSE), Université de Bordeaux $Bordeaux, France",
"---	$Centrum voor Economische Studiën, Faculteit Economie en Bedrijfswetenschappen, KU Leuven $Leuven, Belgium",
"262	$Department of Agricultural and Resource Economics, University of California-Davis $Davis, California (USA)",
"263	$Jeb E. Brooks School of Public Policy, Cornell University $Ithaca, New York (USA)",
"---	$International Bank for Reconstruction & Development (IBRD), World Bank Group $Washington, District of Columbia (USA)",
"264	$Kelley School of Business, Indiana University $Bloomington, Indiana (USA)",
"---	$Economic Growth Center, Economics Department, Yale University $New Haven, Connecticut (USA)",
"265	$de Nederlandsche Bank $Amsterdam, Netherlands",
"---	$Economic Science Institute (ESI), Argyros School of Business and Economics, Chapman University $Orange, California (USA)",
"266	$Facultad de Economía, Universidad de los Andes (Colombia) $Bogotá, Colombia",
"---	$Institutionen för Nationalekonomi med Statistik, Handelshögskolan, Göteborgs Universitet $Göteborg, Sweden",
"267	$Fachbereich Wirtschaftswissenschaften, Universität Konstanz $Konstanz, Germany",
"268	$INSEAD $Fontainebleau, France",
"---	$Department of Economics, Faculty of Business and Economics, University of Melbourne $Melbourne, Australia",
"269	$Economics Department, University of Missouri $Columbia, Missouri (USA)",
"270	$EconomiX, Université Paris-Nanterre (Paris X) $Nanterre, France",
"---	$Centro de Estudios Economicos Regionales (CEER), Banco de la Republica de Colombia $Cartagena, Colombia",
"271	$Rady School of Management, University of California-San Diego (UCSD) $La Jolla, California (USA)",
"272	$Department of Economics, Carleton University $Ottawa, Canada",
"---	$Department of Economics, Carol Martin Gatton College of Business and Economics, University of Kentucky $Lexington, Kentucky (USA)",
"---	$Departament d'Economia i Història Econòmica, Universitat Autònoma de Barcelona, Barcelona School of Economics (BSE) $Barcelona, Spain",
"---	$Institut d'Anàlisi Econòmica CSIC (IAE-CSIC), Barcelona School of Economics (BSE) $Barcelona, Spain",
"273	$Faculté de droit, d'économie et de finance, Université du Luxembourg $Luxembourg, Luxembourg",
"---	$Départment Économie et Sciences de la Décision, HEC Paris (École des Hautes Études Commerciales) $Jouy-en-Josas, France",
"---	$Department of Econometrics and Business Statistics, Monash Business School, Monash University $Melbourne, Australia",
"274	$Department of Economics, Korea University $Seoul, South Korea",
"275	$Warrington College of Business, University of Florida $Gainesville, Florida (USA)",
"276	$College of Business, University of Illinois at Urbana-Champaign $Urbana-Champaign, Illinois (USA)",
"---	$Centre de recherche en Économie (OFCE), Sciences économiques, Sciences Po $Paris, France",
"277	$Institut für Arbeitsmarkt- und Berufsforschung (IAB) $Nürnberg, Germany",
"278	$Swiss Finance Institute $Genève/Zürich, Switzerland",
"---	$Department of Economics, Business School, Deakin University $Melbourne, Australia",
"279	$Singapore Management University $Singapore, Singapore",
"---	$Départment d'économétrie et d'économie politique (DEEP), Faculté des Hautes Études Commerciales (HEC), Université de Lausanne $Lausanne, Switzerland",
"280	$Management School, Lancaster University $Lancaster, United Kingdom",
"281	$Department of Agricultural and Resource Economics, North Carolina State University $Raleigh, North Carolina (USA)",
"282	$IESE Business School, Universidad de Navarra $Barcelona, Spain",
"283	$Institut für Volkswirtschaftslehre, Johannes-Kepler-Universität Linz $Linz, Austria",
"---	$Economic Research Division, Federal Reserve Bank of Richmond $Richmond, Virginia (USA)",
"284	$Department of Agricultural Economics, Purdue University $West Lafayette, Indiana (USA)",
"---	$Center for Research in Econometric Analysis of Time Series (CREATES), Institut for Økonomi, Aarhus Universitet $Aarhus, Denmark",
"---	$Department of Economics, Terry College of Business, University of Georgia $Athens, Georgia (USA)",
"285	$Lille Économie et Management (LEM) $Lille, France",
"286	$Department of Economics, Trinity College Dublin $Dublin, Ireland",
"---	$International Economics Section, Department of Economics, Princeton University $Princeton, New Jersey (USA)",
"287	$Facultad de Economía, Universidad de València $València, Spain",
"288	$Central University of Finance and Economics (CUFE) $Beijing, China",
"289	$Sveriges Riksbank $Stockholm, Sweden",
"---	$Dipartimento di Finanza, Università Commerciale Luigi Bocconi $Milano, Italy",
"290	$University of Piraeus $Piraeus, Greece",
"291	$Wirtschaftswissenschaftliches Zentrum, Universität Basel $Basel, Switzerland",
"292	$Laboratory of Economics and Management (LEM), Scuola Superiore Sant'Anna $Pisa, Italy",
"293	$Business School, University of Exeter $Exeter, United Kingdom",
"294	$Cardiff Business School, Cardiff University $Cardiff, United Kingdom",
"295	$William E. Simon Graduate School of Business Administration, University of Rochester $Rochester, New York (USA)",
"296	$Schweizerische Nationalbank (SNB) $Bern/Zürich, Switzerland",
"---	$Arndt-Corden Department of Economics, Crawford School of Public Policy, Australian National University $Canberra, Australia",
"297	$Facultad de Economía y Empresa, Universidad de Zaragoza $Zaragoza, Spain",
"---	$Economics Group, Nuffield College, Department of Economics, Oxford University $Oxford, United Kingdom",
"298	$Department of Economics, Rice University $Houston, Texas (USA)",
"299	$Department of Economics, University of Houston $Houston, Texas (USA)",
"---	$Applied Economics Workshop, Booth School of Business, University of Chicago $Chicago, Illinois (USA)",
"300	$Fanhai International School of Finance, Fudan University $Shanghai, China",
"301	$Economics Department, University of Strathclyde $Glasgow, United Kingdom",
"---	$Economic Research, Federal Reserve Bank of Boston $Boston, Massachusetts (USA)",
"302	$Robert H. Smith School of Business, University of Maryland $College Park, Maryland (USA)",
"303	$Department of Economics, Royal Holloway $Egham, United Kingdom",
"304	$Waikato Management School, University of Waikato $Hamilton, New Zealand",
"305	$Facoltà di Economia Giorgio Fuà, Università Politecnica delle Marche $Ancona, Italy",
"306	$Tepper School of Business Administration, Carnegie Mellon University $Pittsburgh, Pennsylvania (USA)",
"---	$Center for Global Management, Anderson Graduate School of Management, University of California-Los Angeles (UCLA) $Los Angeles, California (USA)",
"307	$Wirtschaftswissenschaftliche Fakultät, Humboldt-Universität Berlin $Berlin, Germany",
"---	$Econometrisch Instituut, Faculteit der Economische Wetenschappen, Erasmus Universiteit Rotterdam $Rotterdam, Netherlands",
"---	$School of Economics, Singapore Management University $Singapore, Singapore",
"---	$Economic Analysis & Policy Group (EAP), Walter A. Haas School of Business, University of California-Berkeley $Berkeley, California (USA)",
"308	$Department of Economics, European University Institute $Firenze, Italy",
"309	$Guanghua School of Management, Peking University $Beijing, China",
"---	$Institut für Volkswirtschaftslehre, Fakultät für Wirtschaftswissenschaften, Universität Wien $Wien, Austria",
"310	$School of Economics, University of Kent $Canterbury, United Kingdom",
"311	$Department of Applied Economics, College of Agricultural, Food, and Environmental Sciences, University of Minnesota-St. Paul $St. Paul, Minnesota (USA)",
"312	$Scuola di Economia e Statistica, Università degli Studi di Milano-Bicocca $Milano, Italy",
"313	$Département d'Économie, Université d'Ottawa $Ottawa, Canada",
"---	$Finance Department, London School of Economics (LSE) $London, United Kingdom",
"314	$Escola de Economia de São Paulo (EESP), Fundação Getúlio Vargas (FGV) $São Paulo, Brazil",
"315	$Geneva School of Economics and Management, Université de Genève $Genève, Switzerland",
"316	$Bayes Business School, City University $London, United Kingdom",
"317	$Department of Economics, Tulane University $New Orleans, Louisiana (USA)",
"---	$Melbourne Institute of Applied Economic and Social Research (MIAESR), Faculty of Business and Economics, University of Melbourne $Melbourne, Australia",
"318	$Department of Economics, York University $Toronto, Canada",
"319	$Nationale Bank van België/Banque national de Belqique (BNB) $Bruxelles/Brussel, Belgium",
"320	$Théorie Économique, Modélisation, Application (THEMA), Université de Cergy-Pontoise $Cergy-Pontoise, France",
"321	$College of Business, University of Wyoming $Laramie, Wyoming (USA)",
"322	$Facultad de Ciencias Económicas y Empresariales, Universidad Complutense de Madrid $Madrid, Spain",
"323	$LeBow College of Business, Drexel University $Philadelphia, Pennsylvania (USA)",
"324	$Center for Energy and Environmental Policy Research (CEEP), Beijing Institute of Technology $Beijing, China",
"---	$Economics Discipline Group, Business School, University of Technology Sydney $Sydney, Australia",
"325	$EPGE Escola Brasileira de Economia e Finanças, Fundação Getúlio Vargas (FGV) $Rio de Janeiro, Brazil",
"---	$Department of Economics, College of Business, University of Wyoming $Laramie, Wyoming (USA)",
"326	$Institutet för Social Forskning (SOFI), Stockholms Universitet $Stockholm, Sweden",
"327	$Lerner College of Business and Economics, University of Delaware $Newark, Delaware (USA)",
"328	$Scuola di Economia e Management, Università degli Studi di Firenze $Firenze, Italy",
"329	$Department of Economics, University of North Carolina-Chapel-Hill $Chapel Hill, North Carolina (USA)",
"330	$Facultad de Economía y Empresa, Universidad del País Vasco - Euskal Herriko Unibertsitatea $Bilbao, Spain",
"331	$Fakultät für Wirtschafts- und Sozialwissenschaften, Ruprecht-Karls-Universität Heidelberg $Heidelberg, Germany",
"---	$Department of Economics, Miami Herbert Business School, University of Miami $Coral Gables, Florida (USA)",
"332	$Banco de Portugal $Lisboa, Portugal",
"333	$Wirtschaftswissenschaftliche Fakultät, Heinriche-Heine-Universität Düsseldorf $Düsseldorf, Germany",
"---	$Laboratoire d'Économie de Dauphine (LEDa), Université Paris-Dauphine (Paris IX) $Paris, France",
"334	$H. John Heinz III School of Public Policy and Management, Carnegie Mellon University $Pittsburgh, Pennsylvania (USA)",
"335	$School of Economics, Universiteit Utrecht $Utrecht, Netherlands",
"---	$Dipartimento di Scienze per l'Economia e l'Impresa, Scuola di Economia e Management, Università degli Studi di Firenze $Firenze, Italy",
"336	$Faculty of Economics, Keio University $Tokyo, Japan",
"---	$Alfred-Weber-Institut für Wirtschaftswissenschaften, Fakultät für Wirtschafts- und Sozialwissenschaften, Ruprecht-Karls-Universität Heidelberg $Heidelberg, Germany",
"337	$Department of Economics, Wellesley College $Wellesley, Massachusetts (USA)",
"338	$École Universitaire de Recherche d'Économie et de Management (ELMI), Université Côte d'Azur $Nice, France",
"---	$Department of Economics, Lerner College of Business and Economics, University of Delaware $Newark, Delaware (USA)",
"339	$Department of International Development (Queen Elizabeth House), Oxford University $Oxford, United Kingdom",
"340	$Fachbereich Wirtschaftswissenschaft, Freie Universität Berlin $Berlin, Germany",
"341	$School of Business, Leicester University $Leicester, United Kingdom",
"---	$Dipartimento di Economia, Metodi Quantitativi e Strategie d'Impresa (DEMS), Scuola di Economia e Statistica, Università degli Studi di Milano-Bicocca $Milano, Italy",
"342	$Facultad de Ciencia Económicas y Administrativas, Pontificia Universidad Católica de Chile $Santiago, Chile",
"---	$Social Policy Evaluation, Analysis and Research Centre (SPEAR), Research School of Economics, College of Business and Economics, Australian National University $Canberra, Australia",
"---	$Department of Economics, Waikato Management School, University of Waikato $Hamilton, New Zealand",
"---	$Amsterdam School of Economics, Faculteit Economie en Bedrijfskunde, Universiteit van Amsterdam $Amsterdam, Netherlands",
"---	$Düsseldorf Institute for Competition Economics (DICE), Wirtschaftswissenschaftliche Fakultät, Heinriche-Heine-Universität Düsseldorf $Düsseldorf, Germany",
"---	$Dipartimento di Economia e Diritto, Facoltà di Economia, Sapienza Università di Roma $Roma, Italy",
"343	$National Graduate Institute for Policy Studies (GRIPS) $Tokyo, Japan",
"344	$Gordon Lang School of Business and Economics, University of Guelph $Guelph, Canada",
"---	$Groupe de REcherche en Droit, Économie, Gestion (GREDEG), École Universitaire de Recherche d'Économie et de Management (ELMI), Université Côte d'Azur $Nice, France",
"345	$Business School, University of Sydney $Sydney, Australia",
"346	$Culverhouse College of Business, University of Alabama-Tuscaloosa $Tuscaloosa, Alabama (USA)",
"347	$Département de Sciences Économiques, Université de Montréal $Montréal, Canada",
"348	$École des Sciences de la Gestion (ESG), Université du Québec à Montréal (UQAM) $Montréal, Canada",
"349	$Federal Reserve Bank of Kansas City $Kansas City, Missouri (USA)",
"---	$Finance Department, Robert H. Smith School of Business, University of Maryland $College Park, Maryland (USA)",
"350	$Department of Agricultural and Consumer Economics, University of Illinois at Urbana-Champaign $Urbana-Champaign, Illinois (USA)",
"---	$Department of Economics, Management School, Lancaster University $Lancaster, United Kingdom",
"351	$Warwick Business School, University of Warwick $Coventry, United Kingdom",
"352	$Faculty of Economics and Management, University of Cyprus $Nicosia, Cyprus",
"353	$Department of Economics, Southern Methodist University $Dallas, Texas (USA)",
"---	$Department of Economics, Tepper School of Business Administration, Carnegie Mellon University $Pittsburgh, Pennsylvania (USA)",
"---	$Department of Management, London School of Economics (LSE) $London, United Kingdom",
"354	$Department of Economics, University of Alberta $Edmonton, Canada",
"355	$Economic and Social Research Institute (ESRI) $Dublin, Ireland",
"356	$Business School, Hong Kong University of Science and Technology (HKUST) $Kowloon, Hong Kong",
"357	$Department of Economics, University of Sheffield $Sheffield, United Kingdom",
"358	$Department of Economics, Florida State University $Tallahassee, Florida (USA)",
"359	$Department of Agricultural & Applied Economics, University of Wisconsin-Madison $Madison, Wisconsin (USA)",
"360	$Questrom School of Business, Boston University $Boston, Massachusetts (USA)",
"361	$Center for Economic Research and Graduate Education and Economics Institute (CERGE-EI) $Praha, Czech Republic",
"362	$Bureau d'Économie Théorique et Appliquée (BETA) $Nancy/Strasbourg, France",
"363	$Kauppakorkeakoulu, Aalto-yliopisto $Helsinki, Finland",
"364	$McCombs School of Business, University of Texas-Austin $Austin, Texas (USA)",
"365	$Business School, King's College London $London, United Kingdom",
"366	$Business School, University of Western Australia $Perth, Australia",
"367	$Leibniz-Institut für Wirtschaftsforschung Halle (IWH) $Halle, Germany",
"368	$Groupe d'Analyse et de Théorie Économique Lyon St-Étienne (GATE Lyon St-Étienne), Université de Lyon $Lyon, France",
"369	$Institute for Policy Research (IPR), Northwestern University $Evanston, Illinois (USA)",
"---	$Department Volkswirtschaft, WU Wirtschaftsuniversität Wien $Wien, Austria",
"---	$Centre for the Study of African Economies (CSAE), Department of Economics, Oxford University $Oxford, United Kingdom",
"370	$Department of Economics, University of Illinois at Chicago $Chicago, Illinois (USA)",
"371	$Business School, University of Auckland $Auckland, New Zealand",
"372	$Department of Economics, Graduate Center, City University of New York (CUNY) $New York City, New York (USA)",
"---	$Research in Economics and Mathematics (REM), Instituto Superior de Economia e Gestão (ISEG), Universidade de Lisboa $Lisboa, Portugal",
"373	$RWI - Leibniz-Institut für Wirtschaftsforschung $Essen, Germany",
"374	$Wellington School of Business and Government, Victoria University of Wellington $Wellington, New Zealand",
"375	$Dipartimento di Economia e Finanza (DEF), Libera Università Internazionale degli Studi Sociali Guido Carli (LUISS) $Roma, Italy",
"376	$School of Business, University of Wisconsin-Madison $Madison, Wisconsin (USA)",
"377	$École d'Économie, Université Clermont Auvergne $Clermont-Ferrand, France",
"378	$Johnson Graduate School of Management, Cornell University $Ithaca, New York (USA)",
"---	$Department of Economics and Finance, Gordon Lang School of Business and Economics, University of Guelph $Guelph, Canada",
"379	$Business School, Durham University $Durham, United Kingdom",
"380	$Gerald R. Ford School of Public Policy, University of Michigan $Ann Arbor, Michigan (USA)",
"381	$Department of Economics, University of California-Riverside $Riverside, California (USA)",
"382	$Institut für Volkswirtschaftslehre, Christian-Albrechts-Universität Kiel $Kiel, Germany",
"---	$Department of Economics, Faculty of Economics and Management, University of Cyprus $Nicosia, Cyprus",
"383	$Collegio Carlo Alberto, Università degli Studi di Torino $Torino, Italy",
"---	$Département des Sciences Économiques, École des Sciences de la Gestion (ESG), Université du Québec à Montréal (UQAM) $Montréal, Canada",
"---	$Dipartimento di Scienze Economiche e Sociali, Facoltà di Economia Giorgio Fuà, Università Politecnica delle Marche $Ancona, Italy",
"384	$Faculty of Economic and Management Sciences, University of Pretoria $Pretoria, South Africa",
"---	$Department of Finance, Stockholm School of Economics $Stockholm, Sweden",
"385	$Faculté de droit, d'économie et de gestion, Université d'Orléans $Orléans, France",
"386	$International Economics Department, School of Advanced International Studies, Johns Hopkins University $Washington, District of Columbia (USA)",
"---	$Centre for Decision Research and Experimental Economics (CeDEx), School of Economics, University of Nottingham $Nottingham, United Kingdom",
"---	$Centre for Applied Macroeconomic Analysis (CAMA), Crawford School of Public Policy, Australian National University $Canberra, Australia",
"---	$Financial Markets Group (FMG), London School of Economics (LSE) $London, United Kingdom",
"387	$Max-Planck-Institut zur Erforschung von Gemeinschaftsgütern, Max-Planck-Gesellschaft $Bonn, Germany",
"---	$Centre d'Études et de Recherches sur le Développement International (CERDI), École d'Économie, Université Clermont Auvergne $Clermont-Ferrand, France",
"388	$Frank Batten School of Leadership and Public Policy, University of Virginia $Charlottesville, Virginia (USA)",
"389	$Szkoła Główna Handlowa w Warszawie $Warszawa, Poland",
"390	$School of Economics and Management, Tsinghua University $Beijing, China",
"391	$Bank of Greece $Athens, Greece",
"392	$Spears School of Business, Oklahoma State University $Stillwater, Oklahoma (USA)",
"---	$Laboratoire d'Économie d'Orléans (LEO), Faculté de droit, d'économie et de gestion, Université d'Orléans $Orléans, France",
"---	$Dipartimento di Economia e Finanza, Dipartimenti e Istituti di Scienze Economiche, Università Cattolica del Sacro Cuore $Milano, Italy",
"393	$Oesterreichische Nationalbank $Wien, Austria",
"394	$Wirtschaftswissenschaftlichen Fakultät, Eberhard-Karls-Universität Tübingen $Tübingen, Germany",
"395	$College of Business, Florida Atlantic University $Boca Raton, Florida (USA)",
"---	$Department of Economics, Faculty of Economic and Management Sciences, University of Pretoria $Pretoria, South Africa",
"---	$Managerial Economics and Decision Sciences (MEDS), Kellogg Graduate School of Management, Northwestern University $Evanston, Illinois (USA)",
"---	$Department of Business Economics and Public Policy, Ross School of Business, University of Michigan $Ann Arbor, Michigan (USA)",
"---	$Mossavar-Rahmani Center for Business and Government, Harvard Kennedy School, Harvard University $Cambridge, Massachusetts (USA)",
"---	$Department of Economics, Finance and Legal Studies, Culverhouse College of Business, University of Alabama-Tuscaloosa $Tuscaloosa, Alabama (USA)",
"396	$Schar School of Policy and Government, George Mason University $Arlington, Virginia (USA)",
"---	$Department of Finance, College of Business, University of Illinois at Urbana-Champaign $Urbana-Champaign, Illinois (USA)",
"397	$School of Public and Environmental Affairs, Indiana University $Bloomington, Indiana (USA)",
"398	$Dipartimento di Scienze Economico-Sociali e Matematico-Statistiche, Università degli Studi di Torino $Torino, Italy",
"---	$Département d'Économie et de Management, Faculté de droit, d'économie et de finance, Université du Luxembourg $Luxembourg, Luxembourg",
"---	$Institutt for Samfunnsøkonomi, BI Handelshøyskolen $Oslo, Norway",
"---	$Groningen Growth and Development Centre (GGDC), Faculteit Economie en Bedrijfskunde, Rijksuniversiteit Groningen $Groningen, Netherlands",
"---	$Department of Finance, McCombs School of Business, University of Texas-Austin $Austin, Texas (USA)",
"399	$Haslam College of Business, University of Tennessee-Knoxville $Knoxville, Tennessee (USA)",
"---	$Bendheim Center for Finance, Department of Economics, Princeton University $Princeton, New Jersey (USA)",
"---	$Unitat de Fonaments de l'Anàlisi Econòmica, Departament d'Economia i Història Econòmica, Universitat Autònoma de Barcelona, Barcelona School of Economics (BSE) $Barcelona, Spain",
"400	$Department of Economics and Finance, Brunel University London $Uxbridge, United Kingdom",
"---	$Robert D. Burch Center for Tax Policy and Public Finance, Department of Economics, University of California-Berkeley $Berkeley, California (USA)",
"---	$Institut de Recherche Économique et Sociale (IRES), Louvain Institute of Data Analysis and Modelling in Economics and Statistics (LIDAM), Université Catholique de Louvain $Louvain-la-Neuve, Belgium",
"---	$Department of Economics, Business School, University of Auckland $Auckland, New Zealand",
"401	$School of Economics and Public Policy, University of Adelaide $Adelaide, Australia",
"---	$ESRC Centre for the Microeconomic Analysis of Public Policy (CPP), Institute for Fiscal Studies (IFS) $London, United Kingdom",
"---	$Department of Economics, Business School, University of Exeter $Exeter, United Kingdom",
"402	$Department of Economics, Bar Ilan University $Ramat-Gan, Israel",
"403	$Fakultät für Volkswirtschaft und Statistik, Leopold-Franzens-Universität Innsbruck $Innsbruck, Austria",
"---	$School of Economics, LeBow College of Business, Drexel University $Philadelphia, Pennsylvania (USA)",
"404	$McCourt School of Public Policy, Georgetown University $Washington, District of Columbia (USA)",
"405	$Carlson School of Management, University of Minnesota $Minneapolis, Minnesota (USA)",
"406	$Michael G. Foster School of Business, University of Washington $Seattle, Washington (USA)",
"407	$Graduate School of Management, University of California-Davis $Davis, California (USA)",
"408	$Facoltà di Economia / Wirtschaftswissenschaftliche Fakutät, Libera Università di Bolzano / Freie Universität Bozen $Bozen-Bolzano, Italy",
"409	$Suomen Pankki $Helsinki, Finland",
"410	$Scheller College of Business, Georgia Institute of Technology $Atlanta, Georgia (USA)",
"411	$Business School, National University of Singapore (NUS) $Singapore, Singapore",
"412	$Asian Development Bank $Manila, Philippines",
"413	$David Eccles School of Business, University of Utah $Salt Lake City, Utah (USA)",
"414	$Carey Business School, Johns Hopkins University $Baltimore, Maryland (USA)",
"415	$İktisat Bölümü, Bilkent Üniversitesi $Ankara, Turkey",
"416	$Department of Economics, University of Victoria $Victoria, Canada",
"417	$Department of Economics, University of Hawaii-Manoa $Manoa, Hawaii (USA)",
"418	$Economics Department, University of Wisconsin $Milwaukee, Wisconsin (USA)",
"419	$Wallace E. Carroll School of Management, Boston College $Chestnut Hill, Massachusetts (USA)",
"420	$Directorate-General Economic and Financial Affairs (ECFIN), European Commission $Bruxelles/Brussel, Belgium",
"421	$Wirtschaftswissenschaftliche Fakultät, Georg-August-Universität Göttingen $Göttingen, Germany",
"422	$Smeal College of Business Administration, Pennsylvania State University $State College, Pennsylvania (USA)",
"423	$Stiftelsen Frischsenteret for samfunnsøkonomisk forskning, Universitetet i Oslo $Oslo, Norway",
"424	$Department of Global Health and Population, Harvard T. H. Chan School of Public Health, Harvard University $Cambridge, Massachusetts (USA)",
"---	$Instituto de Economía, Facultad de Ciencia Económicas y Administrativas, Pontificia Universidad Católica de Chile $Santiago, Chile",
"---	$China Economics and Management Academy, Central University of Finance and Economics (CUFE) $Beijing, China",
"425	$Department of Land Economy, University of Cambridge $Cambridge, United Kingdom",
"426	$Wirtschaftswissenschaftliche Fakultät, Leibniz Universität Hannover $Hannover, Germany",
"427	$Wirtschafts- und Sozialwissenschaftliche Fakultät, Friedrich-Alexander-Universität Erlangen-Nürnberg $Erlangen-Nürnberg, Germany",
"428	$Department of Economics, Mathematics and Statistics, Birkbeck College $London, United Kingdom",
"429	$Institute of Economics, Academia Sinica $Taipei, Taiwan",
"430	$Research Institute for Economics and Business Administration (RIEB), Kobe University $Kobe, Japan",
"---	$Directorate for Employment, Labour and Social Affairs (ELS), Organisation de Coopération et de Développement Économiques (OCDE) $Paris, France",
"431	$Luxembourg Institute of Socio-Economic Research (LISER, CEPS/INSTEAD) $Esch-sur-Alzette, Luxembourg",
"432	$Business School, University of Nottingham $Nottingham, United Kingdom",
"433	$Henley Business School, University of Reading $Reading, United Kingdom",
"434	$Division of Economics, Nanyang Technological University $Singapore, Singapore",
"435	$Department of Economics, University of Texas-Dallas $Dallas, Texas (USA)",
"---	$Department of Social Policy, London School of Economics (LSE) $London, United Kingdom",
"436	$New Economic School (NES) $Moscow, Russia",
"---	$Department of Economics, Business School, University of Western Australia $Perth, Australia",
"437	$Essex Business School, University of Essex $Colchester, United Kingdom",
"438	$Department of Economics, State University of New York-Binghamton (SUNY) $Binghamton, New York (USA)",
"439	$Alliance Manchester Business School, University of Manchester $Manchester, United Kingdom",
"440	$Faculty of Commerce, University of Cape Town $Cape Town, South Africa",
"441	$School of Business, University of Alberta $Edmonton, Canada",
"442	$School of Global Policy and Strategy, University of California-San Diego (UCSD) $La Jolla, California (USA)",
"443	$School of Economics, University of East Anglia $Norwich, United Kingdom",
"444	$Hankamer School of Business, Baylor University $Waco, Texas (USA)",
"---	$Økonomisk Institut, Copenhagen Business School $Frederiksberg, Denmark",
"---	$Unidade de Estudos sobre Complexidade e Economia (UECE), Research in Economics and Mathematics (REM), Instituto Superior de Economia e Gestão (ISEG), Universidade de Lisboa $Lisboa, Portugal",
]

import pandas as pd

# Initialize lists to hold the parsed data
ranks = []
academic_units = []
locations = []

# Process each entry
for entry in data:
    parts = entry.split('$')
    ranks.append(parts[0].strip())
    academic_units.append(parts[1].strip())
    locations.append(parts[2].strip())

# Create a DataFrame
df = pd.DataFrame({
    'rank': ranks,
    'academic_unit': academic_units,
    'location': locations
})

# Recursive function to find the last valid rank
def find_last_valid_rank(df, index):
    if index < 0:
        return None
    rank = df.loc[index, 'rank']
    if rank != '---':
        return rank
    return find_last_valid_rank(df, index - 1)

# Replace '---' ranks with the previous actual rank
for i in range(len(df)):
    if df.loc[i, 'rank'] == '---':
        df.loc[i, 'rank'] = find_last_valid_rank(df, i - 1)


# Split academic_unit into academic_unit and university
def split_academic_unit(academic_unit):
    parts = academic_unit.split(',', 1)
    if len(parts) > 1:
        return parts[0].strip(), parts[1].strip()
    return "", academic_unit.strip()

df[['academic_unit', 'university']] = df['academic_unit'].apply(lambda x: pd.Series(split_academic_unit(x)))

# Save the DataFrame to a CSV file
df.to_csv('economics_institutions_sample.csv', index=False)
